import '~/styles/globals.css'
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '~/trpc/react'
import {ColorSchemeScript, createTheme, MantineProvider} from "@mantine/core";
import {Navbar} from "~/app/_components/navbar";
import {SessionProvider} from "next-auth/react";
export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}


export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html className={GeistSans.className} lang="en" suppressHydrationWarning={true}>
            <head>
                <ColorSchemeScript defaultColorScheme="auto" />
            </head>
            <body>
                <SessionProvider>
                    <MantineProvider>
                        <TRPCReactProvider>
                            <Navbar />
                            {children}
                        </TRPCReactProvider>
                    </MantineProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
